### ISSUE TITLE
New pymatgen breaks lobster and phonopy workflows

### ISSUE THREAD

**Issue by utf** [materialsproject/atomate2#739] opened 2024-02-24 19:33 UTC
Updating pymatgen and lobsterpy to the latest versions breaks the phonon and lobster workflows.

**Comment by naik-aakash** [comment] 2024-02-27 08:51
Hi @utf , the lobster workflows should be fixed once the mp-api issue with pymatgen is sorted out. Currently, it cannot support latest pymatgen release i.e `pymatgen==2024.2.23`.

And it seems this is already being worked on https://github.com/materialsproject/api/issues/887

I will raise a PR for Phonon workflow fix in sometime today 😃

**Comment by utf** [comment] 2024-02-27 09:07
Thanks @naik-aakash and @JaGeo. Are you saying that all we need to do is update pymatgen and lobsterpy? If so, please could you raise a PR?

**Comment by naik-aakash** [comment] 2024-02-27 09:15
> @naik-aakash I think the mp api issue is already resolved in the latest pymatgen

The issue is latest mp-api pins pymatgen version explicitly to be <2024.2.20 and we need  pymatgen v2024.2.23 

So dependencies cannot get installed https://github.com/materialsproject/atomate2/pull/723 to proceed to tests

**Comment by naik-aakash** [comment] 2024-02-27 11:34
> > @naik-aakash I think the mp api issue is already resolved in the latest pymatgen
> 
> The issue is latest mp-api pins pymatgen version explicitly to be <2024.2.20 and we need pymatgen v2024.2.23 @utf 
> 
> So dependencies cannot get installed #723 to proceed to tests

**Closed** 2024-02-28 10:22 UTC
