### ISSUE TITLE
BUG: package version compatibility issue arises with pydantic >= 2.0

### ISSUE THREAD

**Issue by qchempku2017** [materialsproject/atomate2#536] opened 2023-09-28 21:57 UTC
**Describe the bug**
After emmet-core >= 0.69.5 and jobflow >= 0.1.13, pip install will automatically install pydantic == 2.4.3 as required by these new pacakges. However, the current atomate2 release is not supported by pydantic > 2.0 as the following error will occur:

Traceback (most recent call last):
  File "/home/zhongpc/xiefy/test_chgnet_atomate/chgnet_relax.py", line 1, in <module>
    from atomate2.forcefields.jobs import CHGNetRelaxMaker
  File "/home/zhongpc/anaconda3/envs/chgnet/lib/python3.9/site-packages/atomate2/__init__.py", line 4, in <module>
    from atomate2.settings import Atomate2Settings
  File "/home/zhongpc/anaconda3/envs/chgnet/lib/python3.9/site-packages/atomate2/settings.py", line 6, in <module>
    from pydantic import BaseSettings, Field, root_validator
  File "/home/zhongpc/anaconda3/envs/chgnet/lib/python3.9/site-packages/pydantic/__init__.py", line 218, in __getattr__
    return _getattr_migration(attr_name)
  File "/home/zhongpc/anaconda3/envs/chgnet/lib/python3.9/site-packages/pydantic/_migration.py", line 294, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.4/migration/#basesettings-has-moved-to-pydantic-settings for more details.

Forcibly downgrading pydantic to 1.10.13 will give the following pip error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
emmet-core 0.69.5 requires pydantic>=2.0, but you have pydantic 1.10.13 which is incompatible.
jobflow 0.1.14 requires pydantic>=2.0.1, but you have pydantic 1.10.13 which is incompatible.
maggma 0.57.0 requires pydantic>=2.0, but you have pydantic 1.10.13 which is incompatible.
pydantic-settings 2.0.3 requires pydantic>=2.0.1, but you have pydantic 1.10.13 which is incompatible.

And the following import error:
Traceback (most recent call last):
  File "/home/zhongpc/xiefy/test_chgnet_atomate/chgnet_relax.py", line 1, in <module>
    from atomate2.forcefields.jobs import CHGNetRelaxMaker
  File "/home/zhongpc/anaconda3/envs/chgnet/lib/python3.9/site-packages/atomate2/forcefields/jobs.py", line 9, in <module>
    from jobflow import Maker, job
  File "/home/zhongpc/anaconda3/envs/chgnet/lib/python3.9/site-packages/jobflow/__init__.py", line 4, in <module>
    from jobflow.core.flow import Flow, JobOrder
  File "/home/zhongpc/anaconda3/envs/chgnet/lib/python3.9/site-packages/jobflow/core/__init__.py", line 3, in <module>
    from jobflow.core import flow, job, maker, reference, state, store
  File "/home/zhongpc/anaconda3/envs/chgnet/lib/python3.9/site-packages/jobflow/core/flow.py", line 13, in <module>
    from jobflow.core.reference import find_and_get_references
  File "/home/zhongpc/anaconda3/envs/chgnet/lib/python3.9/site-packages/jobflow/core/reference.py", line 11, in <module>
    from pydantic.v1.utils import lenient_issubclass
ModuleNotFoundError: No module named 'pydantic.v1'

**To Reproduce**
1. pip install atomate2 from in fresh conda environment
2. Try to import any Maker in atomate2.

**Expected behavior**
Package versions should not have any conflict.

**Comment by utf** [comment] 2023-09-28 22:02
For now, you can install atomate2 using the strict dependencies and it should work fine. E.g.,
```bash
pip install atomate2[strict]
```
or if installing from source
```bash
pip install .[strict]
```

**Comment by utf** [comment] 2023-09-28 22:03
Closing as a duplicate of #535

**Closed by utf** 2023-09-28 22:03 UTC
