### ISSUE TITLE
BUG: Forcefield relaxmaker jobs fails due to BSONObj size exceeds 16MB for large structures 

### ISSUE THREAD

**Issue by naik-aakash** [materialsproject/atomate2#703] opened 2024-02-06 20:50 UTC
**Describe the bug**
Relax jobs using forcefields fails as the forcefield taskdoc stores all the ionic steps leading to cross the size limit

# Steps to reproduce
1.Run relax jobs using mace forcefield with Fire optimizer for a cell containing more than 1000 atoms with a force requirement of 0.0001

# Possible solution
1. Modify the default interval arg of relax maker from 1 to 100 / larger number (this solution should potentially work as we tested using LBFGS optimizer of ase instead of default Fire optimzer, and same job then runs without any issue as LBFGS stores 100 steps at max) 
2.  arg to allow users to skip storing ionic step data in taskdoc 

Any thoughts on this or other ideas to tackle this issue are welcome.

**Comment by naik-aakash** [comment] 2024-02-06 20:54
Sorry found a way to set the number of steps we store.

**Comment by JaGeo** [comment] 2024-02-06 20:56
Still, it might be worth solving this with a sensible default

**Comment by naik-aakash** [comment] 2024-02-06 20:58
Okay I reopen this issue then. 😅

**Comment by utf** [comment] 2024-02-15 10:48
Thanks for raising this. I think this is a duplicate of #515, so I will close this issue and move the comments across.

**Closed by utf** 2024-02-15 10:48 UTC
